```cs
using System;

public class Program
{
    public static void Foo<T>()
        where T : new()
    {
        T t = new T();
        if (typeof(T) == t.GetType())
            Console.Write("0");
        else
            Console.Write("1");
    }
    
    public static void Main()
    {
        try
        {
            Foo<int>();
            Foo<int?>();
        }
        catch
        {
            Console.Write("2");
        }
    }
}
```

Answer: 02

SharpLab: https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYCMBYAUH1AZgAINTMB2PAbzwEgjyA2UgFmIDEB7LgHgBUAfAAoAlPToB3ABYBTMLOL9iIYlFmSx9Wrjp1lwYgF41GpWIDcEgJYAzYsOABPAA6yut4f1HGTwAHQA4rLA/K6yYuK6egDCXFAAzlwANrL+AOpg1sARAEQADLmiVtGyyQmyEnRxiSlpmdl5mEUldAC+9PQY6NoSwGBOEjp6dNx81lDAIsVVY7wTwAD8063tEgDGAIbA69JDVTVJqRlZOcK56C0SHbo3bUA

Hint:
<code>int?</code> denotes a nullable <code>int</code>. What do you get if you call the default constructor for a nullable <code>int</code>?

Explanation:
The first call to <code>Foo</code> works completely as you'd expect and prints "0". The default constructor for an <code>int</code> just produces the value 0.

The second call uses a <b>nullable</b> int as the generic type. Default constructing a nullable int like so: <code>var a = new int?();</code> will simply produce the value <code>null</code>. We then try to call <code>t.GetType()</code>, but <code>t</code> is <code>null</code>, so the function throws a null reference exception, and we enter the exception handler, printing "2".
